[versions]
junit = "5.10.3"

[libraries]
junit-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit" }
wodt-wldt = { module = "io.github.webbasedwodt:wldt-wodt-adapter", version = "3.0.0" }

[bundles]
java-testing = [ "junit-api" ]

[plugins]
java-qa = { id = "org.danilopianini.gradle-java-qa", version = "1.57.1"}
